name: "Lint: sqlfluff"
on:
  workflow_call:
    inputs:
      sha:
        description: 'The git sha to build'
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - name: Run - Lint
        run: |
          make lint