name: "Lint: sqlfluff"
on:
  workflow_call:
    inputs:
      sha:
        description: 'The git sha to build'
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      DOCKER_REGISTRY: "us-central1-docker.pkg.dev"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.sha }}

      - name: Run - Lint
        run: |
          make lint